### ISSUE TITLE
[Baselines] Creating a benchmark for light curve classification

### ISSUE THREAD

**Issue by jeraud** [AstroPile/FlatironMeeting2024#10]
# Creating a benchmark for light curve classification

Contacts: Jeroen Audenaert
Participants: Jeroen Audenaert + anyone interested

## Goals and deliverable
Creating a machine learning benchmark for the classification of light curves from space missions, e.g. based on the Kepler and TESS data sets from [Audenaert et al. (2021)](https://arxiv.org/abs/2107.06301). Related  to #9 .

## Resources needed
Enthusiasm, familiarity with light curves, python, scikit-learn,...
  
## Detailed description
[add additional details  about the project]

**Comment by EiffL** [comment]
Maybe we could merge this into #18 ?

**Comment by jeraud** [comment]
Merged into #18
