### ISSUE TITLE
[Data] Store Time Series Data Locally As Two .parquet Files

### ISSUE THREAD

**Issue by benboyd97** [AstroPile/FlatironMeeting2024#26]
# Store Time Series Data Locally As Two .parquet Files Per Dataset

Originally we were planning on saving the time series files data in the hdf5. format but we've come to the conclusion that instead it's better to save it as two different .parquet files to be stored locally. The idea is that the main file will contain a row for each individual photometric observation, meaning a new row for each object, band and time in one big file. This will of course be a very long table but we can navigate it easily using an object ID and band ID. Importantly this will not store any of the padding. The second table will contain the meta data specific to each object, so there will be a new row for each object containing information about the transient (such as redshift, host galaxy information etc). This means that in the loading stage we will have to find a way to merge these two datasets and transform the observations into the padded format that we discussed earlier: `(n_bands, n_features, seq_len)`. If anyone has any comments let us know!

Contacts:
Participants:
Ben Boyd, Aaron Do, Tom Hehir

## Goals and deliverable
[describe your goals for the week and the deliverables you are aiming for]

## Resources needed
[describe the resources (software, skills, data, or just enthusiasm) needed for this project]
  
## Detailed description
[add additional details  about the project]

**Comment by Smith42** [comment]
Hi Ben, have you looked into storing your var lengthed sequences under the [HuggingFace Sequences Feature](https://huggingface.co/docs/datasets/v2.18.0/en/package_reference/main_classes#datasets.Sequence). This feature natively supports variably lengthed data.

**Comment by mb010** [comment]
Spectral data format decision was [this](https://github.com/AstroPile/FlatironMeeting2024/issues/17#issuecomment-2020821462).

**Comment by benboyd97** [comment]
@Smith42 Hi Mike, I think I misunderstood the problem a little at first. We've decided that it's better to store the data locally in the above format because there's no padding so will take up less space. When it comes to loading the data for the user and for Hugging Face we've decided to include the padding in arrays of size `(n_bands, n_features, seq_len)` since this is easier for the ML models to deal with

**Comment by EiffL** [comment]
So, yeah, the motivation for hdf5 is to enable fast cross-matching. HDF5 is a random access file format, meaning that I can directly go fetch a row without needing to read the entire dataset.
parquet is a **_streaming_** file format, meaning that if I want to read row 10_000 I first need to actually read the first 10_000 rows.

**Comment by EiffL** [comment]
If  we use parquet as storage medium, and you want to cross-match 2 different datasets, you won't have a choice but to read all the data. When you have datasets that are small (up to several 100GB) that's no big deal, but we will generally be dealing with tens of Terabyte, just reading files, with no operation, can take days.

**Comment by benboyd97** [comment]
Ahh ok this makes sense thank you for explaining! I think we were focusing too much about not storing the padding without considering the effect of random access. I'll closes this issue!
